<?php

namespace App\Traits;

use Illuminate\Http\Response;

trait ApiResponser
{
	public function successResponse($data, $code = Response::HTTP_OK)
	{
		//return response()->json(['data' => $data,'site' => 1], $code);
		return response($data, $code)->header('Content-Type','application/json');
	}

	public function validationResponse($data, $code = Response::HTTP_OK){
		return response()->json(['data' => $data], $code);
	}

	//error reponse generated by the api gateway itself
	public function errorResponse($message,$code)
	{
		return response()->json(['error' => $message, 'code' => $code], $code);
	}

	//error message generated by the API site
	public function errorMessage($message, $code)
	{
		return response($message, $code)->header('Content-Type','application/json');
	}


}